### ISSUE TITLE
Installation os osx/darwin is a bit tricky. Here's instructions which maybe could be extracted to a wiki.

### ISSUE THREAD

**Issue by suvash** [bos/text-icu#10]
So, I failed while trying to use text-icu via cabal on osx/darwin.

After some good search, I found the following instructions to be quite helpful. Not sure where to document it as , but I'm just putting it up here so that it may help people who might run into the same issue.

Maybe this can eventually be pulled out to the project wiki once set up.

```bash
# Make sure the external lib (icu4c) is installed and available via homebrew
brew install icu4c

# If installing in a cabal sandbox which is mostly what i do
# Just add the package to the <project>.cabal file and then run cabal install with additional parameters
cabal install --only-dependencies  --extra-lib-dirs=/usr/local/opt/icu4c/lib/ --extra-include-dirs=/usr/local/opt/icu4c/include

# If not using sandbox, just cabal install with additional parameters to the homebrew install
cabal install text-icu --extra-lib-dirs=/usr/local/opt/icu4c/lib/ --extra-include-dirs=/usr/local/opt/icu4c/include
```

**Comment by gitfoxi** [comment]
Thanks. That was tricky. I had tried using CPPFLAGS and LDFLAGS and PKG_CONFIG_PATH to no avail.

**Comment by FranklinChen** [comment]
I just ran into this, agree that it should somehow be documented.
