### ISSUE TITLE
Unknown block code causes run-time error

### ISSUE THREAD

**Issue by thomasvnoort** [bos/text-icu#2]
The function ```blockCode``` crashes on unknown block codes. It would be nice if that function could become total, for instance by returning ```NoBlock``` for unknown block codes. I understand that the ```Enum``` is derived, so taking care of such a special case might be a bit tricky (or result in a massive hand-written instance).

**Comment by bos** [comment]
This is more of a procedural bug in not keeping up to date with icu releases. I would rather stay in sync with icu than handle "impossible" errors.
